import type { Metadata } from "next";
import "./globals.scss";
import { Spectral, Modern_Antiqua, Spectral_SC } from "next/font/google";
import { CSSProperties } from "react";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Loading from "./components/loading/Loading";

const antiqua = Modern_Antiqua({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-smythe",
});

const spectral = Spectral({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-spectral",
});
export const metadata: Metadata = {
  title: "Fortune",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`light`}
        style={
          {
            "--fontM": antiqua.style.fontFamily,
            "--fontA": spectral.style.fontFamily,
          } as CSSProperties
        }
      >
        <Loading />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
